name: wearit
description: "A new Flutter e-commerce project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 < 4.0.0'

#---PACKAGES---#
dependencies:
  flutter:
    sdk: flutter

  #--Utility Packages--#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  #-Icons-#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #-State management (getx)-#
  get: ^4.6.5
  get_storage: ^2.1.1

  #-Product specific-#
  readmore: ^2.2.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  #-Supabase-#
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0

  #-Firebase-#
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1

#---PACKAGES END---#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--Local Assets--#
  assets:
    - assets/icons/auth/
    - assets/icons/category/
    - assets/icons/brands/
    - assets/images/onboarding/
    - assets/images/status/
    - assets/images/banner/
    - assets/images/products/
    - assets/images/animations/
    - assets/logos/logo_blue.png

  #--Local Fonts--#
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700