name: wearit
description: "A new Flutter e-commerce project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 < 4.0.0'

#---PACKAGES---#
dependencies:
  flutter:
    sdk: flutter

  #--Utility Packages--#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  #-Icons-#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #-State management (getx)-#
  get: ^4.6.5
  get_storage: ^2.1.1

  #-Product specific-#

#---PACKAGES END---#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--Local Assets--#
  assets:
    - assets/icons/
    - assets/images/onboarding/
    - assets/logos/

  #--Local Fonts--#
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700