// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbf0kwqz49KmTFqGf8ZkbsgXfYRBq_Pqs',
    appId: '1:637940962610:web:4976e38c5106251f88b32b',
    messagingSenderId: '637940962610',
    projectId: 'wearit-ffd25',
    authDomain: 'wearit-ffd25.firebaseapp.com',
    storageBucket: 'wearit-ffd25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowykOkvU4fu8wRM4HqG5-0EP9KTWlzRQ',
    appId: '1:637940962610:android:9c8b8bb4f123ae4d88b32b',
    messagingSenderId: '637940962610',
    projectId: 'wearit-ffd25',
    storageBucket: 'wearit-ffd25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADlCUgqLVNmuWlg8BYgAjU9fDgJ8DRe_I',
    appId: '1:637940962610:ios:cd37c4be105b82bf88b32b',
    messagingSenderId: '637940962610',
    projectId: 'wearit-ffd25',
    storageBucket: 'wearit-ffd25.firebasestorage.app',
    androidClientId: '637940962610-955667mqeplo0omdksbn5mtc86c729m2.apps.googleusercontent.com',
    iosClientId: '637940962610-l6u7lck4l37av7vjc4teijms83sv7co4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearIt',
  );

}